### ISSUE TITLE
Add some file head info

### ISSUE THREAD

**Issue by maosuyun2009** [fpoussin/qtcreator-doxygen#15]
Maybe should have a funcation add some infomation in some file head, like this:
/********************************************************************
 * Copyright (c) 2013 XXXXXXXXX.inc
 * All rights reserved.
 *
 * \file    test.cpp
 * \brief   implement functions
 * \version 1.0
 * \author  xxx
 * \Email   xxxx@gmail.com
 * \date    2013-10-11 (auto gen)
 ********************************************************************
 */

**Comment by fpoussin** [comment]
Can you think of a way to make this generic?
* Versions are usually only used on library headers.
* Licenses vary depending on projects.
* Same with author and email

I'm thinking to add a form for licences, to insert/update them on all files.

Pull requests are accepted :)
