### ISSUE TITLE
Does not work with Qt 5.9

### ISSUE THREAD

**Issue by CsatiZoltan** [fpoussin/qtcreator-doxygen#17]
Cannot include *coreplugin*. Not found.

**Comment by fpoussin** [comment]
Hard to solve without any details.

Platform? Qt creator version ?
Which binary did you use?

**Comment by CsatiZoltan** [comment]
Sorry for the lack of details.

QtCreator: Desktop_Qt_5_9_1_MinGW_32bit
OS: Windows 7 64 bit

Did not use your binary, I wanted to build it from source. That's when the errors occurred.
"qtcreatorplugin.pri" not found
The following headers are not found too.
- in doxygenplugin.h:
```
#include <coreplugin/icore.h>
#include <coreplugin/editormanager/ieditor.h>
#include <extensionsystem/iplugin.h>
```
- in doxygenplugin.cpp
```
#include <coreplugin/actionmanager/actioncontainer.h>
#include <coreplugin/actionmanager/actionmanager.h>
#include <coreplugin/actionmanager/command.h>
#include <coreplugin/coreconstants.h>
#include <coreplugin/editormanager/editormanager.h>
#include <coreplugin/icontext.h>
#include <coreplugin/icore.h>
#include <coreplugin/messagemanager.h>
#include <cppeditor/cppeditorconstants.h>
#include <cpptools/cpptoolsconstants.h>
#include <projectexplorer/project.h>
#include <projectexplorer/projectexplorer.h>
#include <projectexplorer/projectexplorerconstants.h>
#include <projectexplorer/projecttree.h>
#include <projectexplorer/session.h>
#include <extensionsystem/pluginmanager.h>
#include <utils/parameteraction.h>
#include <utils/qtcassert.h>
#include <utils/synchronousprocess.h>
#include <QAction>
#include <QMainWindow>
#include <QMenu>
#include <QMessageBox>
```
- not found headers in other files too

**Comment by fpoussin** [comment]
You need to compile qt creator first, then you can compile the plugin.
Adjust the path in the plugins's project files to point to your qt creator source and compiled folders.

**Comment by CsatiZoltan** [comment]
> You need to compile qt creator first, then you can compile the plugin.
So I need the QtCreator source first. Do you have a latest version of compiled QtCreator? If yes, could you please upload the *qtcreator-doxygen* binary for that version too?

**Comment by fpoussin** [comment]
You can find the latest qt creator sources and binaries here: https://www.qt.io/download-open-source/#section-2
There are already binaries in the releases section.

**Comment by CsatiZoltan** [comment]
Ok, thanks.
