### ISSUE TITLE
Qt Creator 4.5

### ISSUE THREAD

**Issue by Supermanu** [fpoussin/qtcreator-doxygen#18]
Hi,
Qt Creator 4.5 is out. Could you compile the related binaries?
Thanks a lot for this plugin!

**Comment by fpoussin** [comment]
Yes, I'm working on it.

**Comment by fpoussin** [comment]
I have compiled the 32 bit binaries for windows, these should work for Qt creator version that comes with the installer.

**Comment by Supermanu** [comment]
Thanks! 👍 
To be honest, I was waiting for the linux binaries as it is used by the AUR archlinux repository. I eventually compiled it thanks to your recent explanations.

**Comment by ufolr** [comment]
Hi bro~Could you compile a windows x64 version for Qt Creator 4.5?

**Comment by fpoussin** [comment]
@ufolr done :)
