### ISSUE TITLE
binary for Qt creator 4.5 on MAC

### ISSUE THREAD

**Issue by seamanj** [fpoussin/qtcreator-doxygen#19]
I am using mac, and I cannot compile the binary from the source code, could u also provide us with the binary code for mac, I will appreciated! Meanwhile, could u elaborate the details about how to compile from the source code in Readme file. thanks again !

**Comment by fpoussin** [comment]
I just updated the readme with instructions, let me know if you need more details.

**Comment by seamanj** [comment]
Many thanks, now I am able to compile the libDoxygen.dylib on my mac, but my qt creator cannot detect it. I put it in my /Users/xxxxx/Qt/Qt Creator.app/Contents/PlugIns and ~/Library/Application Support/QtProject/Qt Creator/plugins. but it doesn't work, how does this happen?

**Comment by seamanj** [comment]
thank u, I sort it out.
![image](https://user-images.githubusercontent.com/10722187/34470471-7f77be34-ef29-11e7-8c1d-2c7ebea3db69.png)

**Comment by fpoussin** [comment]
Great, thanks for the feedback.

**Comment by VincentSit** [comment]
Sharing the plugin I used, it took 20 minutes to compile, may be useful to those in need.

```
$ pwd
/Users/vincentxue/Library/Application Support/QtProject/Qt Creator
$ tree
.
└── plugins
    ├── 4.8.1
    │   └── libDoxygen.dylib
    └── 4.9.82
        └── libDoxygen.dylib

3 directories, 2 files
```

[libDoxygen.dylib-4.9.82.zip](https://github.com/fpoussin/qtcreator-doxygen/files/2879444/libDoxygen.dylib-4.9.82.zip)
[libDoxygen.dylib-4.8.1.zip](https://github.com/fpoussin/qtcreator-doxygen/files/2879440/libDoxygen.dylib-4.8.1.zip)
