### ISSUE TITLE
Is this supposed to work with 4.8.1 ?

### ISSUE THREAD

**Issue by Zeks** [fpoussin/qtcreator-doxygen#24]
I've added the binary to AppData\Local\QtProject\QtCreator\plugins\ but no new plugins appeared in the plugins section of the qtcreator

**Comment by fpoussin** [comment]
Which file did you get?
Are you on OSX?

**Comment by Zeks** [comment]
I am on windows, I tried dropping this file: https://github.com/fpoussin/qtcreator-doxygen/releases/download/v0.4.7/Doxygen-0.4.7-qtc4.8.x-win32.dll into the root of AppData\Local\QtProject\QtCreator\plugins but doxygen record didn't appear in the qt crator plugins list. Though maybe it didn't work because my WIN 10 is 64 bit.

I've since compiled the plugin from source and it installed itself into a subfolder in the QtCreator\plugins maybe that's the reason? Because the compiled one in the subfolder actually works

**Comment by Zeks** [comment]
the automatically generated subfolder name is 4.8.2... (I've built it for the newer qtc) maybe the pre-built also needs to be placed into a subfolder with exact name of the 4.8.x? I got the impression you should drop into the root from instructions on the main page of the repo

**Comment by fpoussin** [comment]
Yes, it needs to be placed in the subfolder of your Qt Creator version.
I will update the instructions, thanks for the feedback.
