### ISSUE TITLE
Could not resolve dependency

### ISSUE THREAD

**Issue by nyckmaia** [fpoussin/qtcreator-doxygen#26]
I'm using Qt Creator IDE 4.9.2 and I downloaded the binary *.dll plugin for Windows 10 x64 and put it on the plugins folder, but when Qt starts, I got this error message:

```
The following plugins have errors and cannot be loaded:
Doxygen

Details:
Could not resolve dependency 'Core(4.7.2)'
Could not resolve dependency 'CppTools(4.7.2)'
Could not resolve dependency 'CppEditor(4.7.2)'
Could not resolve dependency 'ProjectExplorer(4.7.2)'
Could not resolve dependency 'TextEditor(4.7.2)'
```
**What I have to do?**

**Comment by fpoussin** [comment]
You downloaded the wrong dll, in fact there's no dll for 4.9 yet on Windows.

**Comment by nyckmaia** [comment]
Thank you @fpoussin .
Could you please say to me if is possible to compile it on my enviroment and get the *.dll working in my system?

I tried do to it, but I got some compilation errors:
```
C1083: Cannot open include file: 'coreplugin/dialogs/ioptionspage.h': No such file or directory
C1083: Cannot open include file: 'QDialog': No such file or directory
C1083: Cannot open include file: '3rdparty/cplusplus/Symbols.h': No such file or directory
C1083: Cannot open include file: 'QWidget': No such file or directory
C1083: Cannot open include file: 'coreplugin/icore.h': No such file or directory
```
I set the *.pro variables as:
```
QTCREATOR_SOURCES = "C:/Qt/5.13.0/Src"
IDE_BUILD_TREE = "C:/Qt/Tools/QtCreator/bin"
```
**Could you help me?**

**Comment by fpoussin** [comment]
The variables are incorrect, there are build instructions in README.md

**Comment by fpoussin** [comment]
I've added some binaries to the current release.
