### ISSUE TITLE
ui_doxygensettingswidget.h: No such file or directory

### ISSUE THREAD

**Issue by jiqiubo2019** [fpoussin/qtcreator-doxygen#29]
I download the last code, when compiling the fllow error report:
/run/media/root/disk2/download/doxygen_new/qtcreator-doxygen/doxygensettingswidget.cpp:23: error: ui_doxygensettingswidget.h: No such file or directory
 #include "ui_doxygensettingswidget.h"
                                      ^

**Comment by fpoussin** [comment]
Can you paste every command you used to compile?
