### ISSUE TITLE
run the doxygen command in an asynchronous process

### ISSUE THREAD

**Issue by palacaze** [fpoussin/qtcreator-doxygen#3]
Right now rebuilding the docs freezes QtCreator because of the use of a Synchronous process. As it takes several minutes to rebuild the doc this is unbearable for me. (I use the new-ish CLANG_ASSISTED_PARSING = YES option, which does not help at all).

**Comment by fpoussin** [comment]
We can use the QProcess class with signals/slots to make it asyncronous.

**Comment by fpoussin** [comment]
I just pushed some changes, let me know if it works for you.

**Comment by fpoussin** [comment]
Bumping

**Comment by palacaze** [comment]
Hi
I am swamped with work right now, I will test this in a few days.

**Comment by fpoussin** [comment]
Any update?

**Comment by palacaze** [comment]
Ok I tried this and it works for me, thanks.

**Comment by fpoussin** [comment]
Awesome, closing the issue.
