### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by rialbat** [fpoussin/qtcreator-doxygen#34]
I have an error when I try to install the plugin.
![image](https://user-images.githubusercontent.com/47256826/81402766-afb18980-913a-11ea-91e5-da344ee7cd6e.png)

**Comment by fpoussin** [comment]
Can you show a screenshot of the « about » window to verify the Qt creator version?

**Comment by rialbat** [comment]
> Can you show a screenshot of the « about » window to verify the Qt creator version?
![image](https://user-images.githubusercontent.com/47256826/81405522-7ed45300-9140-11ea-8cf8-254e854ecb1d.png)

**Comment by fpoussin** [comment]
You downloaded the wrong plugin version, you need the win32 version, not win64.

**Comment by rialbat** [comment]
Now it's working, thanks!
