### ISSUE TITLE
v0.4.7 for Qt Creator 4.10-13 missing 4.13.x dll

### ISSUE THREAD

**Issue by neomissing** [fpoussin/qtcreator-doxygen#39]
no Doxygen-0.4.7-qtc4.13.x-win32.dll，Can you add to it？thanks。

**Comment by TomMalfrere** [comment]
I have the same problem...
Ik upgraded from QtCreator 4.12 to 4.13 (64bit) and now the Doxygen plugin is no longer working.

**Comment by BeyePa** [comment]
Same problem here, i would love to use doxygen with QT 4.13!

**Comment by meegle84** [comment]
Same problem here!

**Comment by kay54068** [comment]
francescmm is build :

https://github.com/francescmm/qtcreator-doxygen.git

**Comment by fpoussin** [comment]
Hi, I'll release a newer version

**Comment by fpoussin** [comment]
https://github.com/fpoussin/qtcreator-doxygen/releases/tag/v0.4.8
