### ISSUE TITLE
Qt Creator 4.7.2 is not working

### ISSUE THREAD

**Issue by kay54068** [fpoussin/qtcreator-doxygen#43]
hi @fpoussin ,

I try build the source code from QTC v4.7.2, but generate libDoxygen.so is not show on about plugin dialog.
Can you tell me how to fix it?

**Comment by fpoussin** [comment]
Hi, building this tag should work:
https://github.com/fpoussin/qtcreator-doxygen/commit/d1842945a4d65b490e41ccee69635300703da0ec
