### ISSUE TITLE
Qt Creator 4.14.0 - plugin is not working

### ISSUE THREAD

**Issue by sourligas** [fpoussin/qtcreator-doxygen#44]
Hi @fpoussin ,

I upgraded from QtCreator 4.13 to 4.14 (64-bit Linux) and now the Doxygen plugin is no longer working.

Please check it and find below the error messages from Qt Creator.

_Could not resolve dependency 'Core(4.13.2)'
Could not resolve dependency 'CppTools(4.13.2)'
Could not resolve dependency 'CppEditor(4.13.2)'
Could not resolve dependency 'ProjectExplorer(4.13.2)'
Could not resolve dependency 'TextEditor(4.13.2)'_

**Comment by fpoussin** [comment]
Yes, this is normal since the plugin is not built for this version

**Comment by fpoussin** [comment]
I'll release a new version for 4.14

**Comment by sourligas** [comment]
> Yes, this is normal since the plugin is not built for this version

Yes I know that but I posted this issue in order to report it and let you know.

Thanks.

**Comment by meegle84** [comment]
> I'll release a new version for 4.14

hi, any update about that?
