### ISSUE TITLE
mingw32-make: *** [Makefile:46: release] Error 2

### ISSUE THREAD

**Issue by ghost** [fpoussin/qtcreator-doxygen#49]
I want to compile my code with Compile: qmake && make.

https://github.com/PradeepSimba/test/blob/main/.github/workflows/main.yml

But , If I run it comes an error .

https://github.com/PradeepSimba/test/runs/6637488143?check_suite_focus=true#step:7:59

How can I solve this error ?

**Comment by ghost** [comment]
I set `arch: 'win32_mingw53'` .

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        arch: 'win32_mingw53'


But , [error.][1]

How can I solve this ?

  [1]: https://github.com/PradeepSimba/test/runs/6640953756?check_suite_focus=true#step:3:132

**Comment by jurplel** [comment]
try using `win32_mingw81` since qt 5.15.2 has no `win32_mingw53` package.

**Comment by ghost** [comment]
> try using `win32_mingw81` since qt 5.15.2 has no `win32_mingw53` package.

I changed to `win32_mingw81` But , I have this [error][1]

`collect2.exe: error: ld returned 1 exit status`


  [1]: https://github.com/PradeepSimba/test/runs/6646527504?check_suite_focus=true#step:7:124

**Comment by ghost** [comment]
Thanks for your reply and help !!!
