### ISSUE TITLE
please update binaries for latest QtC

### ISSUE THREAD

**Issue by amigo421** [fpoussin/qtcreator-doxygen#6]

**Comment by fpoussin** [comment]
Binaries are already available for the latest version (3.6.1)

**Comment by amigo421** [comment]
ah, I'm using v4rc1

**Comment by fpoussin** [comment]
I added a binary for linux in the latest release.

**Comment by amigo421** [comment]
I'm on WIn10 , just using qtc4rc1 (based on QT5.7)

**Comment by fpoussin** [comment]
Oh ok, this will have to wait a little bit then.

**Comment by amigo421** [comment]
thanks a lot! I'm (as probably some people too) using qtc as IDE only, no any Qt-based projects,I haven't an installed Qt source and even SDK, so the building any components from source would take a lot of time for me, reading build docs, configuring etc.. 
thank you very much that you provide with a binaries!

**Comment by fpoussin** [comment]
You're welcome :)

**Comment by fpoussin** [comment]
I added the windows binaries for qtc 4.0

**Comment by amigo421** [comment]
thanks a lot, just saw your comment, but using a plugin a few days successfully
