### ISSUE TITLE
Doesn't work in Creator 4.0 on Windows

### ISSUE THREAD

**Issue by sqrt** [fpoussin/qtcreator-doxygen#7]
The release page states support for 4.0-rc, but it doesn't work with Qt Creator 4.0.0 Snapshot 417:

The following plugins have errors and cannot be loaded:
&nbsp;&nbsp;Doxygen

Details:
&nbsp;&nbsp;Could not resolve dependency 'Core(3.6.0)'
&nbsp;&nbsp;Could not resolve dependency 'CppTools(3.6.0)'
&nbsp;&nbsp;Could not resolve dependency 'CppEditor(3.6.0)'
&nbsp;&nbsp;Could not resolve dependency 'ProjectExplorer(3.6.0)'
&nbsp;&nbsp;Could not resolve dependency 'TextEditor(3.6.0)'

**Comment by fpoussin** [comment]
Please check the release section, I just added a dll for 4.0.0

**Comment by xgdgsc** [comment]
@fpoussin Can you porvide the dll for 4.0.x? Thanks.

**Comment by fpoussin** [comment]
I added the binary for win32.
I'll make some documentation when I have time, it's really simple.

**Comment by xgdgsc** [comment]
@fpoussin Thanks.
