### ISSUE TITLE
QString = QByteArray

### ISSUE THREAD

**Issue by kodiakz** [fpoussin/qtcreator-doxygen#8]
Compile error:
`
/tmp/qtcreator-doxygen/doxygenplugin.cpp:334: error: no match for 'operator=' (operand types are 'QString' and 'QByteArray')
     response.stdErr = m_process->readAllStandardError();
`

Running on Ubuntu 14.04 with following parms:
`QTCREATOR_SOURCES =/tmp/qt-creator`
`IDE_BUILD_TREE =/tmp/buildqtc`
`IDE_LIBRARY_BASENAME = /opt/Qt5.6.1/Tools/QtCreator/lib`

_/tmp/qt-creator: version 4.01_

**Comment by fpoussin** [comment]
I just rebuilt it successfully using Qt 5.6.0 and Qtc 4.0.0
The operator overload exists: http://doc.qt.io/qt-5/qstring.html#operator-eq-5

Which Qt version are you using?

**Comment by kodiakz** [comment]
Qt5.6.1 from the installer with QtC 4.0.1.
The defines: 
`DEFINES += QT_CREATOR QT_NO_CAST_TO_ASCII QT_RESTRICTED_CAST_FROM_ASCII`
seem to come from the includes:
```
doxygenpro: include($$QTCREATOR_SOURCES/src/qtcreatorplugin.pri) =>
qtcreatorplugin.pri: include(../qtcreator.pri)
```

**Comment by fpoussin** [comment]
QT_NO_CAST_TO_ASCII prevents the overload to work, so I'll have to change the code.
Thanks!

**Comment by fpoussin** [comment]
Can you try to compile the latest master?
